export const skills = [
    ".NET",
    "Access",
    "Adobe Acrobat",
    "Adobe CC",
    "Adobe XD",
    "Amazon Web Services (AWS)",
    "Angular",
    "Apache",
    "Apollo",
    "ArcGIS",
    "ASP.NET",
    "Assembly",
    "AutoCAD",
    "Autodesk Fusion 360",
    "Autodesk Inventor",
    "AWS",
    "AWS Lambda",
    "Azure",
    "Backbone.js",
    "Bash",
    "Bitbucket",
    "Bulma",
    "C",
    "C#",
    "C++",
    "Caddy",
    "Chakra UI",
    "Clojure",
    "Coffeescript",
    "Contentful",
    "Context",
    "CouchDB",
    "CSS",
    "CSV",
    "Cypress",
    "Dart",
    "DaVinci Resolve",
    "Devops",
    "Django",
    "Docker",
    "Dreamweaver",
    "Drupal",
    "DynamoDB",
    "Eclipse",
    "Elasticsearch",
    "Electron",
    "Elixir",
    "Elm",
    "Ember.js",
    "Emotion",
    "Enzyme",
    "Express",
    "F#",
    "Figma",
    "Firebase",
    "Flutter",
    "Foundation",
    "Gatsby",
    "Git",
    "GitHub",
    "Gitlab",
    "Go",
    "Google Adwords",
    "Google Analytics",
    "Google Cloud Platform (GCP)",
    "GraphQL",
    "Gridsome",
    "Hadoop",
    "Haskell",
    "HTML",
    "Hugo",
    "Illustrator",
    "InDesign",
    "Ionic",
    "Jasmin",
    "Java",
    "Javascript",
    "Jekyll",
    "Jenkins",
    "Jest",
    "jQuery",
    "JSON",
    "Kafka",
    "Kotlin",
    "Kubernetes",
    "Laravel",
    "Less",
    "Lightroom",
    "Linux",
    "Lisp",
    "LXC",
    "Materialize CSS",
    "Material-UI",
    "MathML",
    "Matlab",
    "Maven",
    "Maya",
    "Microservices",
    "Microsoft Azure",
    "Microsoft Paint",
    "Miro",
    "MobX",
    "Mocha",
    "MongoDB",
    "MS IIS",
    "Mustache.js",
    "MySQL",
    "NativeScript",
    "Neo4j",
    "Next.js",
    "Nginx",
    "NgRx",
    "Node.js",
    "NodeJS",
    "NoSQL",
    "NoSQL",
    "Nuxt.js",
    "Objective-C",
    "Oracle",
    "Parcel",
    "PEARL",
    "Photoshop",
    "PHP",
    "PostCSS",
    "PostgreSQL",
    "Pug.js",
    "Python",
    "QuickBooks",
    "R",
    "RabbitMQ",
    "React.js",
    "ReactJS",
    "React Native",
    "Redis",
    "Redux",
    "Relay Modern",
    "REST APIs",
    "RethinkDB",
    "Revit",
    "Rhino 3D",
    "rkt",
    "Rollup",
    "Ruby on Rails",
    "Rust",
    "RxJS",
    "Sass",
    "Scala",
    "Scrum",
    "Scss",
    "Semantic UI",
    "SharePoint",
    "Sketch",
    "SketchUp",
    "SolidWorks",
    "Solr",
    "Spring Boot",
    "Spring Framework",
    "SQL",
    "Stencil",
    "Svelte",
    "Swift",
    "Tailwind CSS",
    "TensorFlow",
    "Trello",
    "T-SQL",
    "Typescript",
    "Underscore",
    "Unity",
    "VBA",
    "Visio",
    "Vue.js",
    "Vuepress",
    "VueX",
    "Web Assembly",
    "Web Components",
    "Webpack",
    "Windows Server",
    "Wordpress",
    "XML",
    "XPath"
];

